# Generated by Django 6.1.1 on 2026-09-08 11:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField(unique=True)),
                ('room_type', models.CharField(max_length=50)),
                ('occupied', models.BooleanField(default=False)),
                ('no_occupancy', models.IntegerField()),
                ('total_occupancy', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('std_name', models.CharField(max_length=100)),
                ('std_email', models.EmailField(max_length=254)),
                ('std_fname', models.CharField(max_length=100)),
                ('std_mname', models.CharField(max_length=100)),
                ('mobile_no', models.IntegerField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')])),
                ('dob', models.DateField()),
                ('profile_pic', models.BinaryField(blank=True, null=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roomno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.roomdetails')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Attendence1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('checkOutDate', models.DateField()),
                ('expCheckInDate', models.DateField()),
                ('reason', models.CharField(max_length=100)),
                ('checkInDate', models.DateField()),
                ('additionReason', models.TextField()),
                ('isavailable', models.BooleanField(default=True)),
                ('payment', models.FloatField()),
                ('roomno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.roomdetails')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('category', models.CharField(max_length=20)),
                ('status', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('roomno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.roomdetails')),
                ('usn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.studentdetails')),
            ],
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField()),
                ('payment_date', models.DateField()),
                ('payment_id', models.CharField(max_length=50)),
                ('reciept_url', models.URLField(blank=True)),
                ('roomno', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.roomdetails')),
                ('usn', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='student.studentdetails')),
            ],
        ),
    ]
