# Generated by Django 6.1.1 on 2026-09-08 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_studentdetails_usn'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentdetails',
            name='reseted_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mobile_no',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='std_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
