# Generated by Django 6.1.1 on 2026-09-08 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_studentdetails_reseted_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='reseted_password',
            field=models.BooleanField(default=False),
        ),
    ]
