# Generated by Django 6.1.1 on 2026-09-08 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_studentdetails_reseted_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='mobile_no',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
