# Generated by Django 6.1.1 on 2026-09-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_alter_studentdetails_mobile_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='profile_pic',
            field=models.BinaryField(null=True),
        ),
    ]
