# Generated by Django 6.1.1 on 2026-09-12 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_alter_complaint_usn_alter_studentattendence_usn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendence1',
            name='days',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='attendence1',
            name='payment',
            field=models.FloatField(default=False),
        ),
    ]
