# Generated by Django 6.1.1 on 2026-09-12 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_studentattendence_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='sample',
            field=models.CharField(max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='attendence1',
            name='checkOutDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendence1',
            name='expCheckInDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='attendence1',
            name='payment',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attendence1',
            name='reason',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
