# Generated by Django 6.1.1 on 2026-09-12 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_rent_sample_alter_attendence1_checkoutdate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rent',
            name='sample',
        ),
    ]
