# Generated by Django 6.1.1 on 2026-09-18 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0011_passwordreset'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(max_length=15),
        ),
    ]
