# Generated by Django 6.1.1 on 2026-09-19 22:26

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0012_alter_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='profile_pic',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='profile_pic'),
        ),
    ]
